### ISSUE TITLE
Adding configure script to sources?

### ISSUE THREAD

**Issue by doragasu** [filler56789/ffdcaenc-2#1]
First of all, thanks for your work making this tool Linux friendly.

I'd like to make a suggestion. Could you please include in future releases the configure script? I know almost nothing about autotools and had to spend some time diggint the net until I found this:
https://bbs.archlinux.org/viewtopic.php?pid=1258673

Having the configure script with the sources (as most source packages do) could save lots of head scratches.

**Comment by filler56789** [comment]
Thanks for the feedback =^.^=

Secondly, and back to the topic, I wrote the file named COMPILE.TXT for a reason ^_~

https://github.com/filler56789/ffdcaenc-2/blob/master/COMPILE.TXT

I too knew nothing about autotools, until the day I found the original dcaenc code (the one written entirely by Alexandr Patrakov). I don't maintain a Linux setup anymore (since 2011, to be exact), but the few regular users of Linux with which I exchanged some private messages, had no actual problems with autoconf (the author of Hybrid, named Selur, just had to update his compiling stuff, I.I.R.C.). Besides, and perhaps more importantly, I have already seen some cases in which the provided ready-made configure scripts became problematic with newer versions of GCC...
_or_ not-compatible with newer versions of MinGW-w64 : -\ So, I decided that it's better not to fix what isn't broken...

P.S.: http://forum.doom9.org/showthread.php?t=170952

**Comment by filler56789** [comment]
Well, only because autoreconf and perl stopped working in my MSYS environment after I moved from Windows XP to Windows 7 x64, I decided to add a configure script to the source-code included in the release.
